config/routes.rb
Rails.application.routes.draw do
  
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: "login", sign_out: "logout", sign_up: "register"  }
  resources :portfolios do
    put :sort, on: :collection
  end
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
  
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Charles Wooley</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<!-- start of blog header -->
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">A collection of my thoughts on a collection of things.</p>
    <span><%= link_to 'New Blog', new_blog_path, class: "btn btn-primary" if logged_in?(:site_admin)  %></span>
    <span><%= link_to 'Topics', topics_path, class: "btn btn-primary" %></span>
  </div>
</div>
<!-- end of blog header -->

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper("nav-link") %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>My name is Charles Wooley, and I am an aspiring developer. Here you will find some of my thoughts on various things like food, dogs, and programming</p>
  </div>
  
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p> <%= link_to topic.title, topic %></p>
    <% end %>
  </div>
  
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/cwooley"><%= fa_icon "github" %> </a></li>
      <!--<li><a href="https://www.facebook.com/charley.wooley.9"><%= fa_icon "facebook" %> </a></li> -->
      <li><a href="https://www.instagram.com/chazman89/"><%= fa_icon "instagram" %> </a></li>
    </ol>
  </div>
</div><!-- /.blog-sidebar -->


        

app/views/shared/_nav.html.erb
    <div class = <%= location %>>
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top | <%= link_to 'View all projects', portfolios_path %></a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Here is a selection of projects that I have worked on in the past. </p>
    <p>
      <%= link_to 'Find out more about me', about_path, class:"btn btn-primary" %>
      <%= link_to "My Blog", blogs_path, class:"btn btn-secondary" %>
    </p>
  </div>
</section>
    

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Here are some examples of work that I have done in the past.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <%= link_to "Charles Wooley", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>